<?php

use Illuminate\Database\Seeder;
use App\Instituicao;

class InstituicaosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $array = [
            ["id" => 63, "name" => "ADAMANTINA - ETEC ENGº HERVAL BELLUSCI - OP 63"],
            ["id" => 55, "name" => "ADAMANTINA - ETEC EUDÉCIO LUIZ VICENTE - OP 55"],
            ["id" => 215, "name" => "AGUAI - ETEC ARNALDO PEREIRA CHEREGATTI - OP 215"],
            ["id" => 6, "name" => "AMERICANA - ETEC POLIVALENTE DE AMERICANA - OP 6"],
            ["id" => 67, "name" => "AMPARO - ETEC JOÃO BELARMINO - OP 67"],
            ["id" => 28, "name" => "ANDRADINA - ETEC SEBASTIANA AUGUSTA DE MORAES - OP 28"],
            ["id" => 281, "name" => "APIAÍ - ETEC DE APIAÍ - OP 281"],
            ["id" => 165, "name" => "ARACATUBA - ETEC DE ARAÇATUBA - OP 165"],
            ["id" => 29, "name" => "ARARAQUARA - ETEC PROFª ANNA DE OLIVEIRA FERRAZ - OP 29"],
            ["id" => 24, "name" => "ARARAS - ETEC PREFEITO ALBERTO FERES - OP 24"],
            ["id" => 274, "name" => "ARUJÁ - ETEC PROF LUIZA MARIA MACHADO - OP 274"],
            ["id" => 95, "name" => "ASSIS - ETEC PEDRO D'ARCÁDIA NETO - OP 95"],
            ["id" => 147, "name" => "ATIBAIA - ETEC PROF. CARMINE BIAGIO TUNDISI - OP 147"],
            ["id" => 145, "name" => "AVARE - ETEC PROF. FAUSTO MAZZOLA - OP 145"],
            ["id" => 40, "name" => "BARRA BONITA - ETEC COMENDADOR JOÃO RAYS - OP 40"],
            ["id" => 108, "name" => "BARRETOS - ETEC CEL. RAPHAEL BRANDÃO - OP 108"],
            ["id" => 245, "name" => "BARUERI - ETEC DE BARUERI - OP 245"],
            ["id" => 30, "name" => "BATATAIS - ETEC ANTONIO DE PADUA CARDOSO - OP 30"],
            ["id" => 135, "name" => "BAURU - ETEC RODRIGUES DE ABREU - OP 135"],
            ["id" => 151, "name" => "BEBEDOURO - ETEC PROF. IDIO ZUCCHI - OP 151"],
            ["id" => 51, "name" => "BOTUCATU - ETEC DR. DOMINGOS MINICUCCI FILHO - OP 51"],
            ["id" => 38, "name" => "CABRALIA PAULISTA - ETEC ASTOR DE MATOS CARVALHO - OP 38"],
            ["id" => 82, "name" => "CACAPAVA - ETEC MACHADO DE ASSIS - OP 82"],
            ["id" => 44, "name" => "CACHOEIRA PAULISTA - ETEC PROF. MARCOS UCHOAS DOS SANTOS - OP 44"],
            ["id" => 62, "name" => "CAFELANDIA - ETEC PROFª HELCY M. MARTINS AGUIAR - OP 62"],
            ["id" => 279, "name" => "CAIEIRAS - ETEC DE CAIEIRAS - OP 279"],
            ["id" => 191, "name" => "CAJAMAR - ETEC GINO REZAGHI - OP 191"],
            ["id" => 43, "name" => "CAMPINAS - ETEC BENTO QUIRINO - OP 43"],
            ["id" => 7, "name" => "CAMPINAS - ETEC CONSELHEIRO ANTÔNIO PRADO - OP 7"],
            ["id" => 201, "name" => "CAMPO LIMPO PAULISTA - ETEC DE CAMPO LIMPO PAULISTA - OP 201"],
            ["id" => 81, "name" => "CANDIDO MOTA - ETEC PROF. LUIZ PIRES BARBOSA - OP 81"],
            ["id" => 124, "name" => "CAPAO BONITO - ETEC DR. CELSO CHARURI - OP 124"],
            ["id" => 213, "name" => "CARAGUATATUBA - ETEC CARAGUATATUBA - OP 213"],
            ["id" => 144, "name" => "CARAPICUIBA - ETEC&nbsp; CARAPICUIBA - OP 144"],
            ["id" => 59, "name" => "CASA BRANCA - ETEC DR. FRANCISCO NOGUEIRA DE LIMA - OP 59"],
            ["id" => 54, "name" => "CATANDUVA - ETEC ELIAS NECHAR - OP 54"],
            ["id" => 72, "name" => "CERQUEIRA CESAR - ETEC PREFEITO JOSÉ ESTEVES - OP 72"],
            ["id" => 248, "name" => "CERQUILHO - ETEC DE CERQUILHO - OP 248"],
            ["id" => 222, "name" => "COTIA - ETEC DE COTIA - OP 222"],
            ["id" => 77, "name" => "CRUZEIRO - ETEC PROF. JOSÉ SANT'ANA DE CASTRO - OP 77"],
            ["id" => 181, "name" => "CUBATAO - ETEC DE CUBATÃO - OP 181"],
            ["id" => 166, "name" => "DIADEMA - ETEC JUSCELINO KUBITSCHECK DE OLIVEIRA - OP 166"],
            ["id" => 52, "name" => "DRACENA - ETEC PROFª CARMELINA BARBOSA - OP 52"],
            ["id" => 241, "name" => "EMBU - ETEC DE EMBU - OP 241"],
            ["id" => 47, "name" => "ESPIRITO STO PINHAL - ETEC DR. CAROLINO DA MOTA E SILVA - OP 47"],
            ["id" => 138, "name" => "FERNANDOPOLIS - ETEC PROFESSOR ARMANDO JOSÉ FARINAZZO - OP 138"],
            ["id" => 170, "name" => "FERRAZ VASCONCELOS - ETEC FERRAZ DE VASCONCELOS - OP 170"],
            ["id" => 78, "name" => "FRANCA - ETEC DR. JÚLIO CARDOSO - OP 78"],
            ["id" => 46, "name" => "FRANCA - ETEC PROF. CARMELINO CORREA JUNIOR - OP 46"],
            ["id" => 231, "name" => "FRANCISCO MORATO - ETEC FRANCISCO MORATO - OP 231"],
            ["id" => 142, "name" => "FRANCO DA ROCHA - ETEC DR. EMILIO H. AGUILAR - OP 142"],
            ["id" => 93, "name" => "GARCA - ETEC DEP. PAULO ORNELLAS C. DE BARROS - OP 93"],
            ["id" => 88, "name" => "GARCA - ETEC MONSENHOR ANTONIO MAGLIANO - OP 88"],
            ["id" => 26, "name" => "GUARATINGUETA - ETEC PROF. ALFREDO DE BARROS SANTOS - OP 26"],
            ["id" => 256, "name" => "GUARIBA - ETEC BENTO CARLOS BOTELHO DO AMARAL - OP 256"],
            ["id" => 152, "name" => "GUARUJA - ETEC ALBERTO SANTOS DUMONT - OP 152"],
            ["id" => 115, "name" => "HORTOLANDIA - ETEC DE HORTOLÂNDIA - OP 115"],
            ["id" => 263, "name" => "IBATE - ETEC DE IBATÉ - OP 263"],
            ["id" => 161, "name" => "IBITINGA - ETEC DE IBITINGA - OP 161"],
            ["id" => 33, "name" => "IGARAPAVA - ETEC ANTONIO JUNQUEIRA DA VEIGA - OP 33"],
            ["id" => 89, "name" => "IGUAPE - ETEC ENGº AGRÔNOMO NARCISO MEDEIROS - OP 89"],
            ["id" => 65, "name" => "ILHA SOLTEIRA - ETEC DE ILHA SOLTEIRA - OP 65"],
            ["id" => 97, "name" => "IPAUSSU - ETEC PEDRO DE LEME BRISOLLA SOBRINHO - OP 97"],
            ["id" => 158, "name" => "ITANHAEM - ETEC DE ITANHAEM - OP 158"],
            ["id" => 261, "name" => "ITAPETININGA - ETEC DARCY PEREIRA DE MORAES - OP 261"],
            ["id" => 53, "name" => "ITAPETININGA - ETEC PROF. EDSON GALVÃO - OP 53"],
            ["id" => 50, "name" => "ITAPEVA - ETEC DR. DEMÉTRIO AZEVEDO JÚNIOR - OP 50"],
            ["id" => 218, "name" => "ITAPIRA - ETEC JOÃO MARIA STEVANATTO - OP 218"],
            ["id" => 249, "name" => "ITAQUAQUECETUBA - ETEC DE ITAQUAQUECETUBA - OP 249"],
            ["id" => 243, "name" => "ITARARE - ETEC ITARARE - OP 243"],
            ["id" => 100, "name" => "ITATIBA - ETEC ROSA PERRONE SCAVONE - OP 100"],
            ["id" => 86, "name" => "ITU - ETEC MARTINHO DI CIERO - OP 86"],
            ["id" => 233, "name" => "ITUVERAVA - ETEC PROF. JOSÉ IGNÁCIO AZEVEDO FILHO - OP 233"],
            ["id" => 48, "name" => "JACAREI - ETEC CÔNEGO JOSÉ BENTO - OP 48"],
            ["id" => 73, "name" => "JALES - ETEC DR. JOSÉ LUIZ VIANA COUTINHO - OP 73"],
            ["id" => 268, "name" => "JANDIRA - ETEC PREFEITO BRAZ PASCHOALIN - OP 268"],
            ["id" => 70, "name" => "JAU - ETEC JOAQUIM FERREIRA DO AMARAL - OP 70"],
            ["id" => 90, "name" => "JAU - ETEC PROF. URIAS FERREIRA - OP 90"],
            ["id" => 42, "name" => "JUNDIAI - ETEC BENEDITO STORANI - OP 42"],
            ["id" => 8, "name" => "JUNDIAI - ETEC VASCO ANTONIO VENCHIARUTTI - OP 8"],
            ["id" => 110, "name" => "LEME - ETEC DEP. SALIM SEDEH - OP 110"],
            ["id" => 244, "name" => "LENCOIS PAULISTA - ETEC CIDADE DO LIVRO - OP 244"],
            ["id" => 104, "name" => "LIMEIRA - ETEC TRAJANO CAMARGO - OP 104"],
            ["id" => 148, "name" => "LINS - ETEC DE LINS - OP 148"],
            ["id" => 240, "name" => "LORENA - ETEC PADRE CARLOS LEONCIO DA SILVA - OP 240"],
            ["id" => 235, "name" => "MAIRINQUE - ETEC MAIRINQUE - OP 235"],
            ["id" => 271, "name" => "Mairiporã - ETEC DE MAIRIPORÃ - OP 271"],
            ["id" => 31, "name" => "MARILIA - ETEC ANTONIO DEVISATE - OP 31"],
            ["id" => 103, "name" => "MATAO - ETEC PROF. DR. SYLVIO DE MATTOS CARVALHO - OP 103"],
            ["id" => 128, "name" => "MAUA - ETEC DE  MAUÁ - OP 128"],
            ["id" => 79, "name" => "MIGUELOPOLIS - ETEC LAURINDO ALVES DE QUEIROZ - OP 79"],
            ["id" => 87, "name" => "MIRASSOL - ETEC PROF. MATHEUS LEITE DE ABREU - OP 87"],
            ["id" => 60, "name" => "MOCOCA - ETEC FRANCISCO GARCIA - OP 60"],
            ["id" => 9, "name" => "MOCOCA - ETEC JOÃO BATISTA DE LIMA FIGUEIREDO - OP 9"],
            ["id" => 15, "name" => "MOGI DAS CRUZES - ETEC PRESIDENTE VARGAS - OP 15"],
            ["id" => 206, "name" => "MOGI GUACU - ETEC EURO ALBINO DE SOUZA - OP 206"],
            ["id" => 96, "name" => "MOGI-MIRIM - ETEC PEDRO FERREIRA ALVES - OP 96"],
            ["id" => 107, "name" => "MONGAGUA - ETEC ADOLPHO BEREZIN - OP 107"],
            ["id" => 255, "name" => "MONTE ALTO - ETEC ALCIDES CESTARI - OP 255"],
            ["id" => 75, "name" => "MONTE APRAZIVEL - ETEC PADRE JOSÉ NUNES DIAS - OP 75"],
            ["id" => 198, "name" => "MONTE MOR - ETEC DE MONTE MOR - OP 198"],
            ["id" => 234, "name" => "NOVA ODESSA - ETEC DE NOVA ODESSA - OP 234"],
            ["id" => 212, "name" => "NOVO HORIZONTE - ETEC PROF. MARINES TEODORO DE F. ALMEIDA - OP 212"],
            ["id" => 232, "name" => "OLIMPIA - ETEC DE OLIMPIA - OP 232"],
            ["id" => 25, "name" => "ORLANDIA - ETEC PROF. ALCIDIO DE SOUZA PRADO - OP 25"],
            ["id" => 242, "name" => "OSASCO - ETEC DR. CELSO GIGLIO - OP 242"],
            ["id" => 149, "name" => "OSASCO - ETEC PROF. ANDRÉ BOGASIAN - OP 149"],
            ["id" => 27, "name" => "OSVALDO CRUZ - ETEC AMIN JUNDI - OP 27"],
            ["id" => 66, "name" => "OURINHOS - ETEC JACINTO FERREIRA DE SÁ - OP 66"],
            ["id" => 164, "name" => "PALMITAL - ETEC PROF. MARIO ANTONIO VERZA - OP 164"],
            ["id" => 39, "name" => "PARAGUACU PAULISTA - ETEC AUGUSTO TORTOLERO ARAUJO - OP 39"],
            ["id" => 69, "name" => "PENAPOLIS - ETEC JOÃO JORGE GERAISSATE - OP 69"],
            ["id" => 266, "name" => "PERUIBE - ETEC DE PERUÍBE - OP 266"],
            ["id" => 203, "name" => "PIEDADE - ETEC DE PIEDADE - OP 203"],
            ["id" => 68, "name" => "PINDAMONHANGABA - ETEC JOÃO GOMES DE ARAÚJO - OP 68"],
            ["id" => 56, "name" => "PIRACICABA - ETEC CEL. FERNANDO FEBELIANO DA COSTA - OP 56"],
            ["id" => 193, "name" => "PIRACICABA - ETEC DEPUTADO ARY DE CAMARGO PEDROSO - OP 193"],
            ["id" => 162, "name" => "PIRAJU - ETEC WALDYR DURON JUNIOR - OP 162"],
            ["id" => 139, "name" => "PIRASSUNUNGA - ETEC TENENTE AVIADOR GUSTAVO KLUG - OP 139"],
            ["id" => 210, "name" => "POA - ETEC DE POÁ - OP 210"],
            ["id" => 289, "name" => "PORTO FELIZ - ETEC DE PORTO FELIZ - OP 289"],
            ["id" => 202, "name" => "PORTO FERREIRA - ETEC PROF. JADYR SALLES - OP 202"],
            ["id" => 153, "name" => "PRAIA GRANDE - ETEC DE PRAIA GRANDE - OP 153"],
            ["id" => 252, "name" => "PRESIDENTE PRUDENTE - ETEC PROF. ADOLPHO ARRUDA MELLO - OP 252"],
            ["id" => 32, "name" => "PRESIDENTE PRUDENTE - ETEC PROF. DR. ANTONIO EUFRASIO DE TOLEDO - OP 32"],
            ["id" => 99, "name" => "PRESIDENTE VENCESLAU - ETEC PROF. MILTON GAZZETTI - OP 99"],
            ["id" => 80, "name" => "QUATA - ETEC DR. LUIZ CESAR COUTO - OP 80"],
            ["id" => 58, "name" => "RANCHARIA - ETEC DEP. FRANCISCO FRANCO (CHIQUITO) - OP 58"],
            ["id" => 239, "name" => "REGISTRO - ETEC DE REGISTRO - OP 239"],
            ["id" => 141, "name" => "RIBEIRAO PIRES - ETEC PROFESSORA MARIA CRISTINA MEDEIROS - OP 141"],
            ["id" => 74, "name" => "RIBEIRAO PRETO - ETEC JOSÉ MARTIMIANO DA SILVA - OP 74"],
            ["id" => 36, "name" => "RIO CLARO - ETEC PROF. ARMANDO BAYEUX DA SILVA - OP 36"],
            ["id" => 71, "name" => "RIO DAS PEDRAS - ETEC DR. JOSÉ COURY - OP 71"],
            ["id" => 282, "name" => "RIO GRANDE DA SERRA - ETEC DE RIO GRANDE DA SERRA - OP 282"],
            ["id" => 94, "name" => "S JOAQUIM DA BARRA - ETEC PEDRO BADRAN - OP 94"],
            ["id" => 83, "name" => "S RITA PASSA QUATRO - ETEC MANOEL DOS REIS ARAÚJO - OP 83"],
            ["id" => 10, "name" => "S. BERNARDO DO CAMPO - ETEC LAURO GOMES - OP 10"],
            ["id" => 98, "name" => "S. JOSE DO RIO PRETO - ETEC PHILADELPHO GOUVEIA NETTO - OP 98"],
            ["id" => 237, "name" => "S. ROSA DE VITERBO - ETEC DE SANTA ROSA DO VITERBO - OP 237"],
            ["id" => 287, "name" => "SANTA CRUZ DAS PALMEIRAS - ETEC JOÃO ELIAS MARGUTTI - OP 287"],
            ["id" => 84, "name" => "SANTA CRUZ RIO PARDO - ETEC ORLANDO QUAGLIATO - OP 84"],
            ["id" => 277, "name" => "SANTA FÉ DO SUL - ETEC DE SANTA FÉ DO SUL - OP 277"],
            ["id" => 219, "name" => "SANTA ISABEL - ETEC SANTA ISABEL - OP 219"],
            ["id" => 262, "name" => "SANTANA DE PARNAIBA - ETEC BARTOLOMEU BUENO DA SILVA - OP 262"],
            ["id" => 187, "name" => "SANTANA DE PARNAIBA - ETEC PROFª ERMELINDA G. TEIXEIRA - OP 187"],
            ["id" => 14, "name" => "SANTO ANDRE - ETEC JÚLIO DE MESQUITA - OP 14"],
            ["id" => 35, "name" => "SANTOS - ETEC ARISTÓTELES FERREIRA - OP 35"],
            ["id" => 122, "name" => "SANTOS - ETEC DONA ESCOLÁSTICA ROSA - OP 122"],
            ["id" => 11, "name" => "SAO CAETANO DO SUL - ETEC JORGE STREET - OP 11"],
            ["id" => 91, "name" => "SAO CARLOS - ETEC PAULINO BOTELHO - OP 91"],
            ["id" => 195, "name" => "SÃO JOSÉ DOS CAMPOS - ETEC PROFESSORA ILZA NASCIMENTO PINTUS - OP 195"],
            ["id" => 150, "name" => "SAO JOSE RIO PARDO - ETEC SÃO JOSÉ DO RIO PARDO - OP 150"],
            ["id" => 102, "name" => "SAO MANUEL - ETEC DONA SEBASTIANA DE BARROS - OP 102"],
            ["id" => 224, "name" => "SAO PAULO - ETEC ABDIAS DO NASCIMENTO - OP 224"],
            ["id" => 23, "name" => "SAO PAULO - ETEC ALBERT EINSTEIN - OP 23"],
            ["id" => 45, "name" => "SAO PAULO - ETEC CARLOS DE CAMPOS - OP 45"],
            ["id" => 223, "name" => "SAO PAULO - ETEC CEPAM - OP 223"],
            ["id" => 211, "name" => "SAO PAULO - ETEC DA ZONA LESTE - OP 211"],
            ["id" => 134, "name" => "SAO PAULO - ETEC DA ZONA SUL - OP 134"],
            ["id" => 180, "name" => "SAO PAULO - ETEC DE ARTES - OP 180"],
            ["id" => 199, "name" => "SAO PAULO - ETEC DE CIDADE TIRADENTES - OP 199"],
            ["id" => 267, "name" => "SAO PAULO - ETEC DE ESPORTES CURT WALTER OTTO BAUMGART - OP 267"],
            ["id" => 118, "name" => "SÃO PAULO - ETEC DE GUAIANAZES - OP 118"],
            ["id" => 205, "name" => "SAO PAULO - ETEC DE HELIOPOLIS - OP 205"],
            ["id" => 285, "name" => "SÃO PAULO - ETEC DE ITAQUERA II - OP 285"],
            ["id" => 18, "name" => "SAO PAULO - ETEC DE SÃO PAULO - OP 18"],
            ["id" => 172, "name" => "SAO PAULO - ETEC DE SAPOPEMBA - OP 172"],
            ["id" => 400, "name" => "SÃO PAULO - ETEC DE TESTE DA ADM CENTRAL - OP 400"],
            ["id" => 185, "name" => "SAO PAULO - ETEC DE VILA FORMOSA - OP 185"],
            ["id" => 154, "name" => "SAO PAULO - ETEC DRª MARIA AUGUSTA SARAIVA - OP 154"],
            ["id" => 13, "name" => "SAO PAULO - ETEC GETULIO VARGAS - OP 13"],
            ["id" => 226, "name" => "SAO PAULO - ETEC GILDO MARÇAL B. BRANDÃO - OP 226"],
            ["id" => 61, "name" => "SAO PAULO - ETEC GUARACY SILVEIRA - OP 61"],
            ["id" => 238, "name" => "SAO PAULO - ETEC IRMÃO AGOSTINA - OP 238"],
            ["id" => 169, "name" => "SAO PAULO - ETEC ITAQUERA - OP 169"],
            ["id" => 228, "name" => "SAO PAULO - ETEC JARAGUÁ - OP 228"],
            ["id" => 221, "name" => "SAO PAULO - ETEC JARDIM ANGELA - OP 221"],
            ["id" => 253, "name" => "SAO PAULO - ETEC JORNALISTA ROBERTO MARINHO - OP 253"],
            ["id" => 76, "name" => "SAO PAULO - ETEC JOSÉ ROCHA MENDES - OP 76"],
            ["id" => 247, "name" => "SAO PAULO - ETEC MANDAQUI - OP 247"],
            ["id" => 85, "name" => "SAO PAULO - ETEC MARTIN LUTHER KING - OP 85"],
            ["id" => 220, "name" => "SAO PAULO - ETEC PARQUE BELEM - OP 220"],
            ["id" => 159, "name" => "SAO PAULO - ETEC PARQUE DA JUVENTUDE - OP 159"],
            ["id" => 229, "name" => "SAO PAULO - ETEC PAULISTANO - OP 229"],
            ["id" => 34, "name" => "SAO PAULO - ETEC PROF. APRIGIO GONZAGA - OP 34"],
            ["id" => 41, "name" => "SAO PAULO - ETEC PROF. BASILIDES DE GODOY - OP 41"],
            ["id" => 64, "name" => "SAO PAULO - ETEC PROF. HORÁCIO AUGUSTO DA SILVEIRA - OP 64"],
            ["id" => 207, "name" => "SAO PAULO - ETEC PROFESSOR ADHEMAR BATISTA HEMÉRITAS - OP 207"],
            ["id" => 12, "name" => "SAO PAULO - ETEC PROFESSOR CAMARGO ARANHA - OP 12"],
            ["id" => 254, "name" => "SAO PAULO - ETEC PROFª DOROTI QUIOMI KANASHIRO TOYOHARA - OP 254"],
            ["id" => 225, "name" => "SAO PAULO - ETEC RAPOSO TAVARES - OP 225"],
            ["id" => 260, "name" => "SAO PAULO - ETEC SANTA IFIGÊNIA - OP 260"],
            ["id" => 227, "name" => "SAO PAULO - ETEC SÃO MATEUS - OP 227"],
            ["id" => 273, "name" => "SÃO PAULO - ETEC SEBRAE - OP 273"],
            ["id" => 200, "name" => "SAO PAULO - ETEC TAKASHI MORITA - OP 200"],
            ["id" => 186, "name" => "SAO PAULO - ETEC TEREZA APARECIDA CARDOSO NUNES DE OLIVEIRA - OP 186"],
            ["id" => 208, "name" => "SAO PAULO - ETEC TIQUATIRA - OP 208"],
            ["id" => 230, "name" => "SAO PAULO - ETEC UIRAPURU - OP 230"],
            ["id" => 236, "name" => "SAO PEDRO - ETEC GUSTAVO TEIXEIRA - OP 236"],
            ["id" => 116, "name" => "SAO ROQUE - ETEC DE SÃO ROQUE - OP 116"],
            ["id" => 188, "name" => "SAO SEBASTIAO - ETEC DE SÃO SEBASTIÃO - OP 188"],
            ["id" => 57, "name" => "SAO SIMAO - ETEC PROF. FRANCISCO DOS SANTOS - OP 57"],
            ["id" => 194, "name" => "SAO VICENTE - ETEC &nbsp;DRª RUTH CARDOSO - OP 194"],
            ["id" => 214, "name" => "SERRANA - ETEC ANGELO CAVALHEIRO - OP 214"],
            ["id" => 264, "name" => "SOROCABA - ETEC ARMANDO PANNUNZIO - OP 264"],
            ["id" => 16, "name" => "SOROCABA - ETEC FERNANDO PRESTES - OP 16"],
            ["id" => 17, "name" => "SOROCABA - ETEC RUBENS DE FARIA E SOUZA - OP 17"],
            ["id" => 117, "name" => "STA BARBARA D'OESTE - ETEC PROF. DR. JOSÉ DAGNONI - OP 117"],
            ["id" => 190, "name" => "SUZANO - ETEC DE SUZANO - OP 190"],
            ["id" => 19, "name" => "TAQUARITINGA - ETEC DR. ADAIL NUNES DA SILVA - OP 19"],
            ["id" => 140, "name" => "TAQUARITUBA - ETEC PROFª TEREZINHA MONTEIRO DOS SANTOS - OP 140"],
            ["id" => 49, "name" => "TAQUARIVAI - ETEC DR. DÁRIO PACHECO PEDROSO - OP 49"],
            ["id" => 101, "name" => "TATUI - ETEC SALES GOMES - OP 101"],
            ["id" => 125, "name" => "TAUBATE - ETEC DR. GERALDO JOSÉ RODRIGUES ALCKMIN - OP 125"],
            ["id" => 156, "name" => "TEODORO SAMPAIO - ETEC PROFESSORA NAIR LUCCAS RIBEIRO - OP 156"],
            ["id" => 246, "name" => "TIETE - ETEC DR. NELSON ALVES VIANNA - OP 246"],
            ["id" => 136, "name" => "TUPA - ETEC PROF. MASSUYUKI KAWANO - OP 136"],
            ["id" => 179, "name" => "VARGEM GRANDE DO SUL - ETEC VARGEM GRANDE DO SUL - OP 179"],
            ["id" => 92, "name" => "VERA CRUZ - ETEC PAULO GUERREIRO FRANCO - OP 92"],
            ["id" => 197, "name" => "VOTORANTIM - ETEC PROFESSOR ELIAS MIGUEL JUNIOR - OP 197"],
            ["id" => 37, "name" => "VOTUPORANGA - ETEC FREI ARNALDO MARIA DE ITAPORANGA - OP 37"]
        ];

        foreach ($array as $a) {
            Instituicao::create($a);
        }
    }
}
